'use strict';
const $=id=>document.getElementById(id);
let token='',current=null,labels=null,prior=null,evaluation=null,busy=false;
const percent=x=>x==null?'Not represented':`${(x*100).toFixed(3)}%`;
function status(message,error=false){$('status').textContent=message;$('status').className=error?'error':'';}
function controls(){ for(const id of ['demo','demo-labels','features-file','labels-file','prior-file','features'])$(id).disabled=busy; $('run').disabled=busy||!token;$('evaluate').disabled=busy||!current||!labels;$('export').disabled=busy||!current; }
async function api(path,body){const options=body?{method:'POST',headers:{'Content-Type':'application/json','X-Session-Token':token},body:JSON.stringify(body)}:{};const response=await fetch(path,options);const result=await response.json();if(!response.ok)throw Error(result.error||'Request failed');return result;}
async function action(fn){if(busy)return;busy=true;controls();try{await fn();}catch(e){status(e.message,true);}finally{busy=false;controls();}}
async function fileJSON(input){const file=input.files[0];if(!file)return null;if(file.size>2000000)throw Error('Use a JSON file under 2 MB.');return {name:file.name,data:JSON.parse(await file.text())};}
function validateReceipt(candidate){
 const categories=['ACCEPT','QUALIFY','SIMULATED','NARRATIVE','QUARANTINE'];
 const probability=v=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1;
 if(!candidate||!Array.isArray(candidate.records)||candidate.records.length===0||candidate.records.length>1000)throw Error('Receipt needs between one and 1,000 records.');
 const ids=new Set();
 for(const r of candidate.records){
  if(!r||typeof r.id!=='string'||r.id.length===0||r.id.length>200||ids.has(r.id))throw Error('Receipt needs unique, nonempty example IDs.');
  if(!categories.includes(r.final_policy_label)||!categories.includes(r.classifier_top_label)||!probability(r.classifier_probability_for_final_label)||!probability(r.classifier_top_label_probability))throw Error('Receipt has missing or invalid labels/probabilities.');
  ids.add(r.id);
 }
 return candidate;
}
function compare(){if(!current||!prior){$('comparison').textContent='Import a previous receipt to compare matching example IDs.';return;}const previous=new Map(prior.records.map(r=>[r.id,r]));let matched=0,changed=0,probChanged=0;for(const r of current.records){const old=previous.get(r.id);if(old){matched++;changed+=old.final_policy_label!==r.final_policy_label;probChanged+=old.classifier_probability_for_final_label!==r.classifier_probability_for_final_label;}}$('comparison').textContent=`${matched} matching IDs · ${changed} changed decisions · ${probChanged} changed final-label probabilities · ${current.records.length-matched} new IDs · ${previous.size-matched} previous-only IDs. Model/configuration equivalence must be reviewed separately.`;}
function render(){const data=current?.records||[];$('count').textContent=data.length;$('overrides').textContent=data.filter(r=>r.policy_override).length;$('accepted').textContent=data.filter(r=>r.final_policy_label==='ACCEPT').length;const mode=$('filter').value;const rows=data.filter(r=>mode==='all'||(mode==='override'?r.policy_override:r.final_policy_label===mode));$('rows').replaceChildren();for(const r of rows){const tr=document.createElement('tr');const id=document.createElement('td');id.textContent=r.id;id.title=r.id;tr.append(id);const decision=document.createElement('td');decision.textContent=`${r.classifier_top_label} → ${r.final_policy_label} · ${r.handling_action||'Legacy receipt'} · evidence: ${r.evidence_category??'unassessed'}`;if(r.policy_override)decision.className='override';tr.append(decision);for(const value of [r.classifier_top_label_probability,r.classifier_probability_for_final_label]){const cell=document.createElement('td');cell.textContent=percent(value);tr.append(cell);}const cell=document.createElement('td');const button=document.createElement('button');button.textContent='View';button.setAttribute('aria-label',`Inspect ${r.id}`);button.onclick=()=>{$('detail-title').textContent=r.id;$('detail-json').textContent=JSON.stringify(r,null,2);$('detail').showModal();};cell.append(button);tr.append(cell);$('rows').append(tr);}if(!rows.length){const tr=document.createElement('tr');const td=document.createElement('td');td.colSpan=5;td.textContent='No decisions match this filter.';td.className='empty';tr.append(td);$('rows').append(tr);}compare();controls();}
function renderEvaluation(){const box=$('evaluation');box.replaceChildren();if(!evaluation){box.textContent='No evaluation for this run. Load reference labels separately.';return;}const title=document.createElement('p');title.textContent=`${evaluation.n} labeled examples · ${evaluation.provenance_declaration.dataset_kind} · External independence not verified`;box.append(title);const dl=document.createElement('dl');for(const [name,value]of [['Accuracy',evaluation.accuracy],['Macro F1 (five classes)',evaluation.macro_f1_fixed_five_classes],['False factual promotion',evaluation.false_factual_promotion_all_examples],['Simulation → fact',evaluation.simulation_to_fact],['Narrative → fact',evaluation.narrative_to_fact],['Chosen-label probability ECE',evaluation.final_label_probability_ece_15]]){const dt=document.createElement('dt');dt.textContent=name;const dd=document.createElement('dd');dd.textContent=percent(value);dl.append(dt,dd);}box.append(dl);}
$('demo').onclick=()=>action(async()=>{$('features').value=JSON.stringify(await api('/api/demo'),null,2);status('Synthetic demo loaded. Run a review to inspect the policy decisions.');});
$('features-file').onchange=()=>action(async()=>{const f=await fileJSON($('features-file'));if(f){$('features').value=JSON.stringify(f.data,null,2);status(`Loaded ${f.name}. Review the input before running.`);}});
$('run').onclick=()=>action(async()=>{status('Computing decisions…');const start=performance.now();const next=await api('/api/predict',JSON.parse($('features').value));current=next;evaluation=null;render();renderEvaluation();$('timing').textContent=`Browser round trip: ${(performance.now()-start).toFixed(1)} ms. First run includes model initialization.`;status('Review complete. Results describe the supplied numeric features.');});
$('filter').onchange=render;
$('labels-file').onchange=()=>action(async()=>{const f=await fileJSON($('labels-file'));if(f){labels=f.data;evaluation=null;renderEvaluation();$('label-name').textContent=f.name;status('Reference labels loaded separately. Their provenance has not been authenticated.');}});
$('demo-labels').onclick=()=>action(async()=>{labels=await api('/api/demo-labels');evaluation=null;renderEvaluation();$('label-name').textContent='Synthetic reference labels';status('Synthetic demo labels loaded. This is a fixture check, not external validation.');});
$('evaluate').onclick=()=>action(async()=>{evaluation=await api('/api/evaluate',{predictions:current,labels});renderEvaluation();status('Reference comparison complete. Review class coverage and source provenance in the export.');});
$('prior-file').onchange=()=>action(async()=>{const f=await fileJSON($('prior-file'));if(f){const candidate=validateReceipt(f.data?.predictions??f.data);prior=candidate;compare();status('Previous receipt loaded for comparison.');}});
$('export').onclick=()=>{const data={schema_version:'1.0',scope:'Local prototype audit; source truth and label independence unverified',predictions:current,evaluation};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='logic-mastery-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Audit export prepared. Keep it with your source and annotation records.');};
$('close-detail').onclick=()=>$('detail').close();
action(async()=>{const session=await api('/api/session');token=session.token;status('Ready. Load the synthetic demo or import a numeric feature dataset.');});
